#NICOLE ORESME Test

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bnf-onto: <http://data.bnf.fr/ontology/bnf-onto/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX marcrel: <http://id.loc.gov/vocabulary/relators/>

SELECT ?name ?bibref
(GROUP_CONCAT(DISTINCT ?uri; SEPARATOR=' ; ')AS ?SUDOC)
(GROUP_CONCAT(DISTINCT ?role; SEPARATOR=' ; ')AS ?Role)
(GROUP_CONCAT(DISTINCT ?sujet; SEPARATOR=' ; ')AS ?RAMEAU)
(GROUP_CONCAT(DISTINCT ?auteur; SEPARATOR=' ; ')AS ?Associated_Author)

	WHERE {
  {<http://www.idref.fr/027053377/id> skos:prefLabel ?name.
  ?uri ?relator <http://www.idref.fr/027053377/id>; dcterms:bibliographicCitation ?bibref.
OPTIONAL{?relator skos:prefLabel ?role}
OPTIONAL{?uri dcterms:subject ?sujet}
OPTIONAL{?uri marcrel:aut ?auteur}
		}
		UNION

		{GRAPH ?g {<http://www.idref.fr/027053377/id> foaf:name ?name ; bnf-onto:FRBNF ?frbnf.}
		 SERVICE <http://data.bnf.fr/sparql>
			{?noticebnf bnf-onto:FRBNF ?frbnf ; foaf:focus ?ressourcebnf
			OPTIONAL {?expression  a <http://rdvocab.info/uri/schema/FRBRentitiesRDA/Expression> ; ?relator ?ressourcebnf.
					  ?relator a skos:Concept ; skos:prefLabel ?role.
	?manifestation <http://rdvocab.info/RDARelationshipsWEMI/expressionManifested> ?expression ; dcterms:title ?titre ; dcterms:date ?date ; rdfs:seeAlso ?uri.}
			 }
		}
	}
